### ISSUE TITLE
Emoji still not rendered in page

### ISSUE THREAD

**Issue by yihuajack** [theme-next/hexo-filter-emoji#8]
I have installed hexo-filter-emoji by `npm install hexo-filter-emoji -g` and modified Hexo _config.yml according to the default options like
```
emoji:
  enable: true
  className: github-emoji
  styles:
  customEmojis:
```
in README. I have executed `hexo clean` before I generate and start the server. However, in web page the emoji like :school: is just plain string. My page is <Blog Folder>/source/about/index.md and the rendered HTML is in <Blog Folder>/public/about/index.html. My blog page is https://yihuajack.github.io.
